Repository Skytils/SkytilsMod, pull requests merged in 2024-03, with the labels that each got.

#391 update mayor techno's utils
  src/main/kotlin/gg/skytils/skytilsmod/core/Config.kt
  src/main/kotlin/gg/skytils/skytilsmod/features/impl/events/TechnoMayor.kt
Labels: Small

#449 feat: quiver display
  src/main/kotlin/gg/skytils/skytilsmod/Skytils.kt
  src/main/kotlin/gg/skytils/skytilsmod/core/Config.kt
  src/main/kotlin/gg/skytils/skytilsmod/features/impl/misc/ItemFeatures.kt
  src/main/kotlin/gg/skytils/skytilsmod/features/impl/misc/QuiverStuff.kt
Labels: Medium

#465 feat: Add Item Cycle
  src/main/kotlin/gg/skytils/skytilsmod/Skytils.kt
  src/main/kotlin/gg/skytils/skytilsmod/commands/impl/ItemCycleCommand.kt
  src/main/kotlin/gg/skytils/skytilsmod/features/impl/handlers/ItemCycle.kt
  src/main/kotlin/gg/skytils/skytilsmod/gui/itemcycle/AddItemCycleGui.kt
  src/main/kotlin/gg/skytils/skytilsmod/gui/itemcycle/ItemCycleConditionGui.kt
  src/main/kotlin/gg/skytils/skytilsmod/gui/itemcycle/ItemCycleGui.kt
  src/main/kotlin/gg/skytils/skytilsmod/gui/itemcycle/condition/ClickConditionGui.kt
  src/main/kotlin/gg/skytils/skytilsmod/gui/itemcycle/condition/IslandConditionGui.kt
  src/main/kotlin/gg/skytils/skytilsmod/gui/itemcycle/condition/ItemConditionGui.kt
Labels: Extra Large

#463 add: Blaze and Vampire slayers to st pv
  src/main/kotlin/gg/skytils/skytilsmod/gui/profile/ProfileGui.kt
  src/main/kotlin/gg/skytils/skytilsmod/gui/profile/components/DungeonsComponent.kt
  src/main/kotlin/gg/skytils/skytilsmod/gui/profile/components/ItemComponent.kt
  src/main/kotlin/gg/skytils/skytilsmod/gui/profile/components/SlayerBossComponent.kt
  src/main/kotlin/gg/skytils/skytilsmod/gui/profile/components/SlayerComponent.kt
Labels: Extra Small

#468 feat: using manual translation
  src/main/resources/assets/skytils/lang/zh_CN.lang
Labels: Extra Large

#471 fix: ice fill 7x7 taking a while to show up
  src/main/kotlin/gg/skytils/skytilsmod/features/impl/dungeons/solvers/IceFillSolver.kt
Labels: Medium

#470 feat: remove click to open maddox
  src/main/kotlin/gg/skytils/skytilsmod/core/Config.kt
  src/main/kotlin/gg/skytils/skytilsmod/features/impl/slayer/SlayerFeatures.kt
  src/main/resources/assets/skytils/lang/en_US.lang
  src/main/resources/assets/skytils/lang/zh_CN.lang
Labels: Extra Small

#467 feat: show item quality
  src/main/kotlin/gg/skytils/skytilsmod/core/Config.kt
  src/main/kotlin/gg/skytils/skytilsmod/features/impl/misc/ItemFeatures.kt
  src/main/resources/assets/skytils/lang/en_US.lang
  src/main/resources/assets/skytils/lang/zh_CN.lang
  src/main/resources/assets/skytils/lang/zh_TW.lang
Labels: Extra Small

#477 add dependency for box starred mobs
  src/main/kotlin/gg/skytils/skytilsmod/core/Config.kt
Labels: Extra Small

#476 fix: always show item highlight
  src/main/java/gg/skytils/skytilsmod/mixins/transformers/gui/MixinGuiIngame.java
  src/main/java/gg/skytils/skytilsmod/mixins/transformers/gui/MixinGuiIngameForge.java
  src/main/kotlin/gg/skytils/skytilsmod/mixins/hooks/gui/GuiIngameForgeHook.kt
Labels: Extra Small
